version: "3"

services:
  go-gurd:
    build: ../
    ports:
      - 8080:8080
    networks:
      - go-guard-mesh
    environment:
      TARGET: http://rserver:5000

  web:
    build: ./rserver
    networks:
      go-guard-mesh:
        aliases:
          - rserver
    expose:
      - 80

networks:
  go-guard-mesh: {}
